### ISSUE TITLE
start publishing yet from the begining

### ISSUE THREAD

**Issue by aremazeilles** [tecnalia-medical-robotics/optoforce_ros#5]
It was preferred to start yet from the beginning the publication of wrench.
We did it so here (hard-coded, not yet pushed), but it could be good adding a param to do so properly.

I'll try creating a branch with such addition during the day.

When doing so, we did not see the message "before full" that used to be presented when the publication was triggered by the topic. Seems to work although

As soon as I push the current version here, I'll add the branch name

**Comment by asierfernandez** [comment]
I've implemented this funtionallity within F_reset branch
